### PR TITLE
Revamp docs

### PR DESCRIPTION
**Pull request by bramtayl**
So... this is a WIP but I'm not sure I'll be able to make much more progress. I've made the following changes:

- Added a github actions infrastructure to build the docs. Also has a lot of other bells and whistles
- Moved lone docstrings to a separate file
- Added a whole bunch of doc tests.
- Unexported a couple of unused and undocumented functions...mostly because I couldn't figure out what they were for.
- Rewrote `@expand_dots`, because it didn't seem to work on 1.4

I haven't documented any of the GR or JuliaCanvas stuff, in part because it's marked as experimental, but mostly because I can't figure it out. I think most of the docs are correct, but I'm sure there's stuff I've gleaned wrong. I'm still confused by why it's necessary to pass empty `QUrl` and `qmlcontext`s.

### CODE REVIEW

**Comment by bramtayl** [comment]
Nevermind, all the exports are back.

**Comment by barche** [comment]
Thanks for this, it already looks quite comprehensive to me. Ready to merge if you are, should anything special be done to make the Github actions work, I've never used those before.

**Comment by bramtayl** [comment]
Np, thanks for a cool package! I don't think that you need to do anything special to set up github actions. I think Documenter will automatically create a `gh-pages` branch for you to host documentation. But I think you will have to tell github manually that `gh-pages` will contain documentation. See the comment [here](https://github.com/JuliaDocs/Documenter.jl/issues/1177#issuecomment-590138234).

Also note that documentation won't build until tests pass...there might be a way to get around this? Once it's up and working, you can delete the travis.yml file. You can disable appveyor too because github actions can test on windows, but you'll have to change the settings to add windows.

Maybe wait a couple of days to merge? I'm still messing around with the package a bit.

**Comment by bramtayl** [comment]
Nevermind, I think I'm happy with this now

**Comment by barche** [comment]
OK, I merged it and removed Travis and Appveyor. Locally on Linux the doctests sometimes give unexpected output due to OpenGL warnings, I don't know how to make the tests ignore that.

**Comment by bramtayl** [comment]
I've never used it, but I think there's a way to filter doctests [here](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Filtering-Doctests)

**Comment by bramtayl** [comment]
@barche I looked at the gh pages branch and there's documentation there! Just enable it by toggle the "Source" option in the GitHub Pages settings (just click settings then scroll down)

**Comment by barche** [comment]
It was all enabled, I think it failed because of https://github.com/JuliaDocs/Documenter.jl/issues/1177. Worked around it by adding a custom token, the docs are there now, thanks!

**Pull request merged**
